<?php

use App\Http\Controllers\Api\AdminApprovalController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AutomationController;
use App\Http\Controllers\Api\BudgetLineController;
use App\Http\Controllers\Api\BusinessIntelligenceController;
use App\Http\Controllers\Api\ComplianceController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DocumentController;
use App\Http\Controllers\Api\DrawingController;
use App\Http\Controllers\Api\EquipmentController;
use App\Http\Controllers\Api\FieldController;
use App\Http\Controllers\Api\FinanceController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OrganizationController;
use App\Http\Controllers\Api\PeopleController;
use App\Http\Controllers\Api\PlatformAdminController;
use App\Http\Controllers\Api\PortalController;
use App\Http\Controllers\Api\ProcurementController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\ProjectTaskController;
use App\Http\Controllers\Api\SalesController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:auth.login');
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:auth.login');
    Route::post('auth/mfa-challenge', [AuthController::class, 'mfaChallenge'])->middleware('throttle:auth.mfa');

    Route::middleware(['auth:sanctum', 'throttle:api'])->group(function (): void {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('security/mfa', [AuthController::class, 'mfaStatus']);
        Route::post('security/mfa/setup', [AuthController::class, 'setupMfa']);
        Route::post('security/mfa/enable', [AuthController::class, 'enableMfa']);
        Route::post('security/mfa/disable', [AuthController::class, 'disableMfa']);
        Route::post('security/mfa/recovery-codes', [AuthController::class, 'regenerateMfaRecoveryCodes']);

        Route::get('dashboard', [DashboardController::class, 'index'])->middleware('permission:reports.view');
        Route::get('reports', [DashboardController::class, 'reports'])->middleware('permission:reports.view');
        Route::get('audit-logs', [DashboardController::class, 'auditLogs'])->middleware('permission:reports.view');
        Route::get('notifications', [NotificationController::class, 'index'])->middleware('permission:reports.view|automation.manage|settings.manage');
        Route::patch('notifications/settings', [NotificationController::class, 'updateSettings'])->middleware('permission:settings.manage|automation.manage');
        Route::post('notifications/{notification}/read', [NotificationController::class, 'markRead'])->middleware('permission:reports.view|automation.manage|settings.manage');
        Route::post('notifications/{notification}/acknowledge', [NotificationController::class, 'acknowledge'])->middleware('permission:reports.view|automation.manage|settings.manage');
        Route::get('platform-admin', [PlatformAdminController::class, 'index'])->middleware('permission:platform.manage');
        Route::post('platform-admin/companies', [PlatformAdminController::class, 'storeCompany'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/companies/{company}', [PlatformAdminController::class, 'updateCompanyAccount'])->middleware('permission:platform.manage');
        Route::delete('platform-admin/companies/{company}', [PlatformAdminController::class, 'archiveCompany'])->middleware('permission:platform.manage');
        Route::post('platform-admin/companies/{companyId}/restore', [PlatformAdminController::class, 'restoreCompany'])->middleware('permission:platform.manage');
        Route::delete('platform-admin/companies/{companyId}/permanent', [PlatformAdminController::class, 'permanentlyDeleteCompany'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/companies/{company}/features/{flag}', [PlatformAdminController::class, 'updateCompanyFeature'])->middleware('permission:platform.manage');
        Route::post('platform-admin/companies/{company}/branding', [PlatformAdminController::class, 'updateBranding'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/companies/{company}/success', [PlatformAdminController::class, 'updateCompanySuccess'])->middleware('permission:platform.manage');
        Route::post('platform-admin/companies/{company}/impersonate', [PlatformAdminController::class, 'startImpersonation'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/features/{flag}', [PlatformAdminController::class, 'updateFeatureFlag'])->middleware('permission:platform.manage');
        Route::post('platform-admin/users', [PlatformAdminController::class, 'storePlatformUser'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/users/{user}', [PlatformAdminController::class, 'updatePlatformUser'])->middleware('permission:platform.manage');
        Route::delete('platform-admin/users/{user}', [PlatformAdminController::class, 'destroyPlatformUser'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/profile', [PlatformAdminController::class, 'updatePlatformProfile'])->middleware('permission:platform.manage');
        Route::post('platform-admin/plans', [PlatformAdminController::class, 'storePlan'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/plans/{plan}', [PlatformAdminController::class, 'updatePlan'])->middleware('permission:platform.manage');
        Route::delete('platform-admin/plans/{plan}', [PlatformAdminController::class, 'destroyPlan'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/subscriptions/{subscription}', [PlatformAdminController::class, 'updateSubscription'])->middleware('permission:platform.manage');
        Route::post('platform-admin/subscriptions/{subscription}/upgrade', [PlatformAdminController::class, 'upgradeSubscription'])->middleware('permission:platform.manage');
        Route::delete('platform-admin/subscriptions/{subscription}', [PlatformAdminController::class, 'destroySubscription'])->middleware('permission:platform.manage');
        Route::post('platform-admin/billing-records', [PlatformAdminController::class, 'storeBillingRecord'])->middleware('permission:platform.manage');
        Route::post('platform-admin/support-tickets', [PlatformAdminController::class, 'storeSupportTicket'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/support-tickets/{ticket}', [PlatformAdminController::class, 'updateSupportTicket'])->middleware('permission:platform.manage');
        Route::post('platform-admin/deployments', [PlatformAdminController::class, 'storeDeployment'])->middleware('permission:platform.manage');
        Route::post('platform-admin/backups', [PlatformAdminController::class, 'storeBackup'])->middleware('permission:platform.manage');
        Route::patch('platform-admin/settings', [PlatformAdminController::class, 'updateSettings'])->middleware('permission:platform.manage');

        Route::get('organization', [OrganizationController::class, 'index']);
        Route::patch('organization/company', [OrganizationController::class, 'updateCompany'])->middleware('permission:settings.manage');
        Route::delete('organization/company', [OrganizationController::class, 'destroyCompany'])->middleware('permission:settings.manage');
        Route::post('organization/branches', [OrganizationController::class, 'storeBranch'])->middleware('permission:settings.manage');
        Route::post('organization/users', [OrganizationController::class, 'storeUser'])->middleware('permission:settings.manage|payroll.manage');
        Route::patch('organization/users/{user}', [OrganizationController::class, 'updateUser'])->middleware('permission:settings.manage|payroll.manage');
        Route::delete('organization/users/{user}', [OrganizationController::class, 'destroyUser'])->middleware('permission:settings.manage|payroll.manage');
        Route::post('organization/roles', [OrganizationController::class, 'storeRole'])->middleware('permission:settings.manage|payroll.manage');
        Route::patch('organization/roles/{role}', [OrganizationController::class, 'updateRole'])->middleware('permission:settings.manage|payroll.manage');
        Route::delete('organization/roles/{role}', [OrganizationController::class, 'destroyRole'])->middleware('permission:settings.manage|payroll.manage');
        Route::post('organization/clients', [OrganizationController::class, 'storeClient'])->middleware('permission:projects.manage');
        Route::patch('organization/clients/{client}', [OrganizationController::class, 'updateClient'])->middleware('permission:settings.manage');
        Route::delete('organization/clients/{client}', [OrganizationController::class, 'destroyClient'])->middleware('permission:settings.manage');
        Route::post('organization/suppliers', [OrganizationController::class, 'storeSupplier'])->middleware('permission:procurement.manage');
        Route::patch('organization/suppliers/{supplier}', [OrganizationController::class, 'updateSupplier'])->middleware('permission:settings.manage');
        Route::delete('organization/suppliers/{supplier}', [OrganizationController::class, 'destroySupplier'])->middleware('permission:settings.manage');
        Route::get('admin/approvals', [AdminApprovalController::class, 'index'])->middleware('permission:settings.manage');
        Route::post('admin/approvals/{type}/{id}/review', [AdminApprovalController::class, 'review'])->middleware('permission:settings.manage');

        Route::get('projects', [ProjectController::class, 'index']);
        Route::post('projects', [ProjectController::class, 'store'])->middleware('permission:projects.manage');
        Route::get('projects/timeline', [ProjectController::class, 'timeline']);
        Route::get('projects/{project}', [ProjectController::class, 'show']);
        Route::patch('projects/{project}', [ProjectController::class, 'update'])->middleware('permission:settings.manage');
        Route::delete('projects/{project}', [ProjectController::class, 'destroy'])->middleware('permission:settings.manage');

        Route::post('projects/{project}/tasks', [ProjectTaskController::class, 'store'])->middleware('permission:projects.manage');
        Route::patch('projects/{project}/tasks/{task}', [ProjectTaskController::class, 'update'])->middleware('permission:projects.manage');
        Route::delete('projects/{project}/tasks/{task}', [ProjectTaskController::class, 'destroy'])->middleware('permission:projects.manage');

        Route::post('projects/{project}/budget-lines', [BudgetLineController::class, 'store'])->middleware('permission:projects.manage');
        Route::patch('projects/{project}/budget-lines/{budgetLine}', [BudgetLineController::class, 'update'])->middleware('permission:projects.manage');
        Route::delete('projects/{project}/budget-lines/{budgetLine}', [BudgetLineController::class, 'destroy'])->middleware('permission:projects.manage');

        Route::get('procurement', [ProcurementController::class, 'index'])->middleware('permission:procurement.manage');
        Route::get('procurement/requisitions', [ProcurementController::class, 'requisitions']);
        Route::post('projects/{project}/requisitions', [ProcurementController::class, 'storeRequisition'])->middleware('permission:procurement.manage');
        Route::patch('procurement/requisitions/{requisition}', [ProcurementController::class, 'updateRequisition'])->middleware('permission:procurement.manage');
        Route::delete('procurement/requisitions/{requisition}', [ProcurementController::class, 'destroyRequisition'])->middleware('permission:procurement.manage');
        Route::post('procurement/requisitions/{requisition}/submit', [ProcurementController::class, 'submitRequisition'])->middleware('permission:procurement.manage');
        Route::post('procurement/requisitions/{requisition}/review', [ProcurementController::class, 'reviewRequisition'])->middleware('permission:procurement.approve');
        Route::post('procurement/requisitions/{requisition}/convert-to-po', [ProcurementController::class, 'convertToPurchaseOrder'])->middleware('permission:procurement.manage');
        Route::post('procurement/requisitions/{requisition}/rfqs', [ProcurementController::class, 'storeRfq'])->middleware('permission:procurement.manage');
        Route::post('procurement/rfqs/{rfq}/quotations', [ProcurementController::class, 'storeSupplierQuotation'])->middleware('permission:procurement.manage');
        Route::post('procurement/quotations/{quotation}/accept', [ProcurementController::class, 'acceptQuotation'])->middleware('permission:procurement.approve');
        Route::post('procurement/quotations/{quotation}/purchase-order', [ProcurementController::class, 'createPurchaseOrderFromQuotation'])->middleware('permission:procurement.manage');

        Route::get('procurement/purchase-orders', [ProcurementController::class, 'purchaseOrders']);
        Route::post('projects/{project}/purchase-orders', [ProcurementController::class, 'storePurchaseOrder'])->middleware('permission:procurement.manage');
        Route::post('procurement/purchase-orders/{purchaseOrder}/transition', [ProcurementController::class, 'transitionPurchaseOrder'])->middleware('permission:procurement.manage');
        Route::post('procurement/purchase-orders/{purchaseOrder}/goods-receipts', [ProcurementController::class, 'storeGoodsReceipt'])->middleware('permission:procurement.manage');
        Route::post('procurement/purchase-orders/{purchaseOrder}/supplier-invoices', [ProcurementController::class, 'storeSupplierInvoice'])->middleware('permission:procurement.manage');
        Route::post('procurement/goods-receipts/{goodsReceipt}/quality-inspections', [ProcurementController::class, 'storeQualityInspection'])->middleware('permission:quality.manage');
        Route::post('procurement/supplier-invoices/{invoice}/approve', [ProcurementController::class, 'approveSupplierInvoice'])->middleware('permission:finance.manage');
        Route::post('procurement/supplier-invoices/{invoice}/payments', [ProcurementController::class, 'recordSupplierPayment'])->middleware('permission:finance.manage');
        Route::post('suppliers/{supplier}/contracts', [ProcurementController::class, 'storeSupplierContract'])->middleware('permission:procurement.manage');

        Route::get('documents', [DocumentController::class, 'index']);
        Route::post('documents', [DocumentController::class, 'store'])->middleware('permission:documents.manage');
        Route::patch('documents/{document}', [DocumentController::class, 'update'])->middleware('permission:documents.manage');
        Route::get('documents/{document}/download', [DocumentController::class, 'download']);
        Route::delete('documents/{document}', [DocumentController::class, 'destroy'])->middleware('permission:documents.manage');

        Route::get('drawings', [DrawingController::class, 'index']);
        Route::post('drawings', [DrawingController::class, 'store'])->middleware('permission:documents.manage');
        Route::post('drawings/{drawing}/revisions', [DrawingController::class, 'revise'])->middleware('permission:documents.manage');
        Route::post('drawings/{drawing}/transition', [DrawingController::class, 'transition'])->middleware('permission:documents.manage');
        Route::post('drawings/{drawing}/markups', [DrawingController::class, 'storeMarkup'])->middleware('permission:documents.manage');
        Route::post('drawing-markups/{markup}/resolve', [DrawingController::class, 'resolveMarkup'])->middleware('permission:documents.manage');
        Route::post('drawings/{drawing}/reviews', [DrawingController::class, 'storeReview'])->middleware('permission:documents.manage');
        Route::get('drawing-revisions/{revision}/download', [DrawingController::class, 'downloadRevision']);

        Route::get('sales', [SalesController::class, 'index'])->middleware('permission:crm.manage|tenders.manage|estimating.manage');
        Route::post('sales/leads', [SalesController::class, 'storeLead'])->middleware('permission:crm.manage');
        Route::patch('sales/leads/{lead}', [SalesController::class, 'updateLead'])->middleware('permission:crm.manage');
        Route::delete('sales/leads/{lead}', [SalesController::class, 'destroyLead'])->middleware('permission:crm.manage');
        Route::post('sales/leads/{lead}/qualify', [SalesController::class, 'qualifyLead'])->middleware('permission:crm.manage');
        Route::post('sales/opportunities', [SalesController::class, 'storeOpportunity'])->middleware('permission:crm.manage');
        Route::post('sales/opportunities/{opportunity}/tenders', [SalesController::class, 'createTenderFromOpportunity'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders', [SalesController::class, 'storeTender'])->middleware('permission:tenders.manage');
        Route::patch('sales/tenders/{tender}', [SalesController::class, 'updateTender'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/submit', [SalesController::class, 'submitTender'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/win', [SalesController::class, 'winTender'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/lose', [SalesController::class, 'loseTender'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/rfis', [SalesController::class, 'storeTenderRfi'])->middleware('permission:tenders.manage');
        Route::post('sales/tender-rfis/{rfi}/respond', [SalesController::class, 'respondTenderRfi'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/documents', [SalesController::class, 'uploadTenderDocument'])->middleware('permission:tenders.manage');
        Route::post('sales/tenders/{tender}/records', [SalesController::class, 'storeTenderRecord'])->middleware('permission:tenders.manage');
        Route::patch('sales/tender-records/{record}', [SalesController::class, 'updateTenderRecord'])->middleware('permission:tenders.manage');
        Route::get('sales/tender-documents/{document}/download', [SalesController::class, 'downloadTenderDocument'])->middleware('permission:tenders.manage');
        Route::post('sales/pricing-items', [SalesController::class, 'storePricingItem'])->middleware('permission:estimating.manage');
        Route::post('sales/estimates', [SalesController::class, 'storeEstimate'])->middleware('permission:estimating.manage');
        Route::post('sales/estimates/{estimate}/lines', [SalesController::class, 'addEstimateLine'])->middleware('permission:estimating.manage');
        Route::post('sales/estimates/{estimate}/approve', [SalesController::class, 'approveEstimate'])->middleware('permission:estimating.manage');

        Route::get('inventory', [InventoryController::class, 'index'])->middleware('permission:inventory.manage');
        Route::post('inventory/warehouses', [InventoryController::class, 'storeWarehouse'])->middleware('permission:inventory.manage');
        Route::patch('inventory/warehouses/{warehouse}', [InventoryController::class, 'updateWarehouse'])->middleware('permission:inventory.manage');
        Route::delete('inventory/warehouses/{warehouse}', [InventoryController::class, 'destroyWarehouse'])->middleware('permission:inventory.manage');
        Route::post('inventory/items', [InventoryController::class, 'storeItem'])->middleware('permission:inventory.manage');
        Route::patch('inventory/items/{item}', [InventoryController::class, 'updateItem'])->middleware('permission:inventory.manage');
        Route::delete('inventory/items/{item}', [InventoryController::class, 'destroyItem'])->middleware('permission:inventory.manage');
        Route::post('inventory/movements', [InventoryController::class, 'moveStock'])->middleware('permission:inventory.manage');
        Route::post('suppliers/{supplier}/prices', [InventoryController::class, 'storeSupplierPrice'])->middleware('permission:suppliers.manage');
        Route::post('suppliers/{supplier}/reviews', [InventoryController::class, 'storeSupplierReview'])->middleware('permission:suppliers.manage');

        Route::get('field', [FieldController::class, 'index'])->middleware('permission:field.manage');
        Route::post('projects/{project}/daily-reports', [FieldController::class, 'storeDailyReport'])->middleware('permission:field.manage');
        Route::post('field/daily-reports/{dailyReport}/transition', [FieldController::class, 'transitionDailyReport'])->middleware('permission:field.manage');
        Route::post('projects/{project}/field-issues', [FieldController::class, 'storeIssue'])->middleware('permission:field.manage');
        Route::patch('field/issues/{issue}', [FieldController::class, 'updateIssue'])->middleware('permission:field.manage');
        Route::delete('field/issues/{issue}', [FieldController::class, 'destroyIssue'])->middleware('permission:field.manage');
        Route::get('field/issues/{issue}/photo', [FieldController::class, 'downloadIssuePhoto'])->middleware('permission:field.manage');
        Route::post('attendance/clock-in', [FieldController::class, 'clockIn'])->middleware('permission:attendance.manage');
        Route::post('attendance/{attendance}/clock-out', [FieldController::class, 'clockOut'])->middleware('permission:attendance.manage');

        Route::get('finance', [FinanceController::class, 'index'])->middleware('permission:finance.manage');
        Route::post('finance/invoices', [FinanceController::class, 'storeInvoice'])->middleware('permission:finance.manage');
        Route::post('finance/invoices/{invoice}/lines', [FinanceController::class, 'addInvoiceLine'])->middleware('permission:finance.manage');
        Route::post('finance/invoices/{invoice}/issue', [FinanceController::class, 'issueInvoice'])->middleware('permission:finance.manage');
        Route::post('finance/invoices/{invoice}/payments', [FinanceController::class, 'recordPayment'])->middleware('permission:finance.manage');
        Route::post('finance/expenses', [FinanceController::class, 'storeExpense'])->middleware('permission:finance.manage');
        Route::post('finance/expenses/{expense}/review', [FinanceController::class, 'reviewExpense'])->middleware('permission:finance.manage');
        Route::post('finance/journal-entries', [FinanceController::class, 'storeJournalEntry'])->middleware('permission:finance.manage');
        Route::post('finance/accounts', [FinanceController::class, 'storeAccount'])->middleware('permission:finance.manage');
        Route::post('finance/bank-accounts', [FinanceController::class, 'storeBankAccount'])->middleware('permission:finance.manage');
        Route::post('finance/bank-reconciliations', [FinanceController::class, 'storeBankReconciliation'])->middleware('permission:finance.manage');
        Route::post('finance/credit-notes', [FinanceController::class, 'storeCreditNote'])->middleware('permission:finance.manage');
        Route::post('finance/retentions', [FinanceController::class, 'storeRetention'])->middleware('permission:finance.manage');
        Route::post('finance/retentions/{retention}/release', [FinanceController::class, 'releaseRetention'])->middleware('permission:finance.manage');
        Route::post('finance/progress-billings', [FinanceController::class, 'storeProgressBilling'])->middleware('permission:finance.manage');
        Route::post('finance/tax-rules', [FinanceController::class, 'storeTaxRule'])->middleware('permission:finance.manage');
        Route::post('finance/cost-centers', [FinanceController::class, 'storeCostCenter'])->middleware('permission:finance.manage');
        Route::post('finance/fixed-assets', [FinanceController::class, 'storeFixedAsset'])->middleware('permission:finance.manage');

        Route::get('people', [PeopleController::class, 'index'])->middleware('permission:payroll.manage');
        Route::post('people/employees', [PeopleController::class, 'storeEmployeeProfile'])->middleware('permission:payroll.manage');
        Route::post('people/job-vacancies', [PeopleController::class, 'storeJobVacancy'])->middleware('permission:payroll.manage');
        Route::post('people/candidates', [PeopleController::class, 'storeCandidate'])->middleware('permission:payroll.manage');
        Route::post('people/applications', [PeopleController::class, 'storeApplication'])->middleware('permission:payroll.manage');
        Route::post('people/applications/{application}/hire', [PeopleController::class, 'hireApplication'])->middleware('permission:payroll.manage');
        Route::post('people/interviews', [PeopleController::class, 'storeInterview'])->middleware('permission:payroll.manage');
        Route::post('people/onboarding-checklists', [PeopleController::class, 'storeOnboardingChecklist'])->middleware('permission:payroll.manage');
        Route::post('people/shifts', [PeopleController::class, 'storeShift'])->middleware('permission:payroll.manage');
        Route::post('people/shift-assignments', [PeopleController::class, 'storeShiftAssignment'])->middleware('permission:payroll.manage');
        Route::post('people/timesheets', [PeopleController::class, 'storeTimesheet'])->middleware('permission:payroll.manage');
        Route::post('people/timesheets/{timesheet}/review', [PeopleController::class, 'reviewTimesheet'])->middleware('permission:payroll.manage');
        Route::post('people/workforce-allocations', [PeopleController::class, 'storeAllocation'])->middleware('permission:payroll.manage');
        Route::post('people/overtime-requests', [PeopleController::class, 'storeOvertimeRequest'])->middleware('permission:payroll.manage');
        Route::post('people/overtime-requests/{overtime}/review', [PeopleController::class, 'reviewOvertimeRequest'])->middleware('permission:payroll.manage');
        Route::post('people/leave-requests', [PeopleController::class, 'storeLeaveRequest'])->middleware('permission:payroll.manage');
        Route::post('people/leave-requests/{leaveRequest}/review', [PeopleController::class, 'reviewLeaveRequest'])->middleware('permission:payroll.manage');
        Route::post('people/payroll-runs', [PeopleController::class, 'storePayrollRun'])->middleware('permission:payroll.manage');
        Route::post('people/payroll-runs/{payrollRun}/approve', [PeopleController::class, 'approvePayrollRun'])->middleware('permission:payroll.manage');
        Route::post('people/benefits', [PeopleController::class, 'storeBenefit'])->middleware('permission:payroll.manage');
        Route::post('people/performance-reviews', [PeopleController::class, 'storePerformanceReview'])->middleware('permission:payroll.manage');
        Route::post('people/training-courses', [PeopleController::class, 'storeTrainingCourse'])->middleware('permission:payroll.manage');
        Route::post('people/training-records', [PeopleController::class, 'storeTrainingRecord'])->middleware('permission:payroll.manage');
        Route::post('people/certifications', [PeopleController::class, 'storeCertification'])->middleware('permission:payroll.manage');
        Route::post('people/ppe-issues', [PeopleController::class, 'storePpeIssue'])->middleware('permission:payroll.manage');
        Route::post('people/contractors', [PeopleController::class, 'storeContractor'])->middleware('permission:payroll.manage');
        Route::post('people/assets', [PeopleController::class, 'storeWorkforceAsset'])->middleware('permission:payroll.manage');
        Route::post('people/documents', [PeopleController::class, 'storeWorkforceDocument'])->middleware('permission:payroll.manage');
        Route::post('people/exit-records', [PeopleController::class, 'storeExitRecord'])->middleware('permission:payroll.manage');

        Route::get('equipment', [EquipmentController::class, 'index'])->middleware('permission:equipment.manage');
        Route::post('equipment/assets', [EquipmentController::class, 'storeAsset'])->middleware('permission:equipment.manage');
        Route::post('equipment/assets/{asset}/assign', [EquipmentController::class, 'assignAsset'])->middleware('permission:equipment.manage');
        Route::post('equipment/assignments/{assignment}/release', [EquipmentController::class, 'releaseAssignment'])->middleware('permission:equipment.manage');
        Route::post('equipment/assets/{asset}/maintenance', [EquipmentController::class, 'storeMaintenance'])->middleware('permission:equipment.manage');
        Route::post('equipment/assets/{asset}/fuel-logs', [EquipmentController::class, 'storeFuelLog'])->middleware('permission:equipment.manage');

        Route::get('compliance', [ComplianceController::class, 'index'])->middleware('permission:quality.manage|safety.manage');
        Route::post('projects/{project}/inspections', [ComplianceController::class, 'storeInspection'])->middleware('permission:quality.manage');
        Route::post('compliance/inspections/{inspection}/complete', [ComplianceController::class, 'completeInspection'])->middleware('permission:quality.manage');
        Route::post('projects/{project}/ncrs', [ComplianceController::class, 'storeNcr'])->middleware('permission:quality.manage');
        Route::post('compliance/ncrs/{ncr}/close', [ComplianceController::class, 'closeNcr'])->middleware('permission:quality.manage');
        Route::post('safety/incidents', [ComplianceController::class, 'storeIncident'])->middleware('permission:safety.manage');
        Route::post('safety/incidents/{incident}/close', [ComplianceController::class, 'closeIncident'])->middleware('permission:safety.manage');
        Route::post('safety/toolbox-talks', [ComplianceController::class, 'storeToolboxTalk'])->middleware('permission:safety.manage');
        Route::post('safety/observations', [ComplianceController::class, 'storeObservation'])->middleware('permission:safety.manage');
        Route::post('safety/observations/{observation}/close', [ComplianceController::class, 'closeObservation'])->middleware('permission:safety.manage');
        Route::post('safety/permits', [ComplianceController::class, 'storePermit'])->middleware('permission:safety.manage');
        Route::post('safety/permits/{permit}/transition', [ComplianceController::class, 'transitionPermit'])->middleware('permission:safety.manage');

        Route::get('portals', [PortalController::class, 'index'])->middleware('permission:portals.manage');
        Route::post('portals/users', [PortalController::class, 'storePortalUser'])->middleware('permission:portals.manage');
        Route::post('portals/users/{portalUser}/access', [PortalController::class, 'grantAccess'])->middleware('permission:portals.manage');
        Route::post('projects/{project}/client-approvals', [PortalController::class, 'storeClientApproval'])->middleware('permission:portals.manage');
        Route::post('portals/client-approvals/{approval}/review', [PortalController::class, 'reviewClientApproval'])->middleware('permission:portals.manage');
        Route::post('projects/{project}/consultant-submittals', [PortalController::class, 'storeConsultantSubmittal'])->middleware('permission:portals.manage');
        Route::post('portals/consultant-submittals/{submittal}/review', [PortalController::class, 'reviewConsultantSubmittal'])->middleware('permission:portals.manage');
        Route::post('projects/{project}/portal-work-items', [PortalController::class, 'storeWorkItem'])->middleware('permission:portals.manage');
        Route::patch('portals/work-items/{workItem}', [PortalController::class, 'updateWorkItem'])->middleware('permission:portals.manage');
        Route::post('portals/work-items/{workItem}/review', [PortalController::class, 'reviewWorkItem'])->middleware('permission:portals.manage');
        Route::delete('portals/work-items/{workItem}', [PortalController::class, 'destroyWorkItem'])->middleware('permission:portals.manage');

        Route::get('bi', [BusinessIntelligenceController::class, 'index'])->middleware('permission:bi.manage');
        Route::post('bi/dashboards', [BusinessIntelligenceController::class, 'storeDashboard'])->middleware('permission:bi.manage');
        Route::patch('bi/dashboards/{dashboard}', [BusinessIntelligenceController::class, 'updateDashboard'])->middleware('permission:bi.manage');
        Route::delete('bi/dashboards/{dashboard}', [BusinessIntelligenceController::class, 'destroyDashboard'])->middleware('permission:bi.manage');
        Route::post('bi/snapshots', [BusinessIntelligenceController::class, 'createSnapshot'])->middleware('permission:bi.manage');

        Route::get('automation', [AutomationController::class, 'index'])->middleware('permission:automation.manage');
        Route::get('automation/catalog', [AutomationController::class, 'catalog'])->middleware('permission:automation.manage');
        Route::post('automation/rules', [AutomationController::class, 'storeRule'])->middleware('permission:automation.manage');
        Route::patch('automation/rules/{rule}', [AutomationController::class, 'updateRule'])->middleware('permission:automation.manage');
        Route::delete('automation/rules/{rule}', [AutomationController::class, 'destroyRule'])->middleware('permission:automation.manage');
        Route::post('automation/rules/{rule}/run', [AutomationController::class, 'runRule'])->middleware('permission:automation.manage');
        Route::post('automation/rules/{rule}/versions/{version}/rollback', [AutomationController::class, 'rollbackVersion'])->middleware('permission:automation.manage');
        Route::post('automation/templates/{template}/instantiate', [AutomationController::class, 'instantiateTemplate'])->middleware('permission:automation.manage');
        Route::post('automation/triggers/{event}', [AutomationController::class, 'triggerEvent'])->middleware('permission:automation.manage');
        Route::post('automation/run-active', [AutomationController::class, 'runActive'])->middleware('permission:automation.manage');
    });
});
